packageExtensions:
  "@nuxt/babel-preset-app@*":
    dependencies:
      sass-loader: 10
      webpack: 4
  "@nuxt/content@*":
    dependencies:
      json5: "*"
  "@nuxt/core@*":
    dependencies:
      unplugin-vue2-script-setup: "*"
  "@nuxt/types@*":
    dependencies:
      webpack: 4
  "@nuxtjs/composition-api@*":
    dependencies:
      unplugin-vue2-script-setup: "*"
  "@nuxtjs/eslint-config-typescript@*":
    dependencies:
      eslint: "*"
  "@nuxtjs/eslint-module@*":
    dependencies:
      webpack: 4
  eslint-plugin-nuxt@*:
    dependencies:
      eslint: "*"
  nuxt-build-optimisations@*:
    dependencies:
      webpack: 4
  nuxt@*:
    dependencies:
      consola: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-1.23.0-20220130.1630.cjs
