packageExtensions:
  "@nuxt/babel-preset-app@*":
    dependencies:
      sass-loader: "*"
  "@nuxt/content@*":
    dependencies:
      json5: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
