backend:
  name: git-gateway
  branch: main
  identity_url: https://gotrue.ec-nordbund.de
  gateway_url: https://gitnet.ec-nordbund.de


publish_mode: editorial_workflow
site_url: https://preview.ec-nordbund.de/
show_preview_links: true

media_folder: static/img
public_folder: /img
locale: 'de'

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
  


collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    delete: false
    slug: '{{year}}-{{slug}}'
    preview_path: "blog/{{year}}-{{slug}}"
    extension: md
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'published', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Haupt-Bild', name: 'featuredImage', widget: 'image', media_folder: '/static/img/veranstaltungen', public_folder: '/img/veranstaltungen', choose_url: false, allow_multiple: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'veranstaltungen'
    label: 'Veranstaltungen'
    folder: 'content/veranstaltung'
    format: 'frontmatter'
    create: true
    delete: false
    slug: '{{year}}{{slug}}'
    preview_path: "veranstaltungen/{{year}}{{slug}}"
    extension: md
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Begin', name: 'begin', widget: 'datetime', format: 'YYYY-MM-DD'}
      - { label: 'Ende', name: 'ende', widget: 'datetime', format: 'YYYY-MM-DD'}
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Haupt-Bild', name: 'featuredImage', widget: 'image', media_folder: '/static/img/veranstaltungen', public_folder: '/img/veranstaltungen', choose_url: false, allow_multiple: false }
      - label: "Bilder"
        name: "images"
        widget: "list"
        field: { label: 'Bild', name: 'i', widget: 'image', media_folder: '/static/img/veranstaltungen', public_folder: '/img/veranstaltungen', choose_url: false, allow_multiple: true }
      - {label: "Ist Juleica Fortblidung", name: "juleica", widget: "boolean", default: false}
      - label: Veranstaltungsort
        name: location
        widget: object
        required: false
        fields:
      - {label: "Veranstaltungsort", name: "veranstaltungsort", widget: "string" }
      - { label: "Breitengrad", name: "lat", widget: "string" }
      - { label: "Längengrad", name: "long", widget: "string" }
      - {label: "Strasse", name: "strasse", widget: "string" }
      - {label: "PLZ", name: "plz", widget: "string" }
      - {label: "Ort", name: "ort", widget: "string" }
      - {label: "min Alter", required: false, name: "minAlter", widget: "number", default: false}
      - {label: "max Alter", required: false, name: "maxAlter", widget: "number", default: false}
      - label: Tags
        name: tags
        widget: list
        default: []
        field: { label: 'Tag', name: 'tag', widget: 'string' }
      - label: Warteliste
        name: warteliste
        widget: object
        fields:
          - {label: "Männlich", name: "männlich", widget: "boolean", default: false}
          - {label: "Weiblich", name: "weiblich", widget: "boolean", default: false}
          - {label: "Allgemein", name: "allgemein", widget: "boolean", default: false}
      - label: Preise
        name: preise
        widget: list
        fields:
          - { label: 'Begin', name: 'begin', widget: 'datetime', format: 'YYYY-MM-DD', required: false, default: null}
          - { label: 'Ende', name: 'ende', widget: 'datetime', format: 'YYYY-MM-DD', required: false, default: null}
          - { label: "Name", name: "label", widget: "string" }
          - { label: "Preis", name: "preis", widget: "number" }
      - label: Anmeldung
        name: anmeldung
        widget: object
        fields:
          - {label: "Deaktiviert", name: "disabled", widget: "boolean", default: true}
          - {label: "Start", name: "startAt", widget: "datetime", default: true, format: 'YYYY-MM-DDTHH:MM:SSZ'}
          - {label: "Mit Essen", name: "hatEssen", widget: "boolean", default: false}
          - {label: "Mit Gesundheitsinformationen", name: "hatGesundheit", widget: "boolean", default: false}
          - {label: "Erlaubnis Boot", name: "hatErlaubnisBoot", widget: "boolean", default: false}
          - {label: "Erlaubnis Klettern", name: "hatErlaubnisKlettern", widget: "boolean", default: false}
          - {label: "Erlaubnis Fahrrad", name: "hatErlaubnisFahrrad", widget: "boolean", default: false}
          - {label: "Erlaubnis Schwimmen", name: "hatErlaubnisSchwimmen", widget: "boolean", default: false}
          - {label: "Erlaubnis sich in 3er Gruppen entfernen", name: "hatErlaubnisSichEntfernen", widget: "boolean", default: false}
          - {label: "Erlaubnis Datenschutz TN-Liste", name: "hatFahrgemeinschaft", widget: "boolean", default: false}
          - {label: "Hat Freizeitleitung Hinweis", name: "hatFreizeitleitung", widget: "boolean", default: false}
          - {label: "min Jahrgang", name: "jahrgangMin", widget: "number", default: false}
          - {label: "max Jahrgang", name: "jahrgangMax", widget: "number", default: false}
          
