backend:
  name: git-gateway
  branch: main
  identity_url: https://gotrue.ec-nordbund.de
  gateway_url: https://gitnet.ec-nordbund.de
  squash_merges: true

# see https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# only uncommet locally!
# local_backend: true

publish_mode: editorial_workflow
site_url: https://www.ec-nordbund.de/
# TODO: replace with SVG image
logo_url: https://www.ec-nordbund.de/icon.png
show_preview_links: true

media_folder: static/img
public_folder: 'img/'
locale: 'de'

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _

collections:
  - label: 'Seiten'
    name: 'pages'
    preview_path: '/'
    editor:
      preview: false
    files:
      - label: 'Startseite'
        name: 'startpage'
        file: 'content/pages/startseite.yml'
        fields:
          - label: 'Countdown'
            name: 'countdown'
            widget: 'object'
            summary: '{{text.vor}}{{date}}'
            fields:
              - { label: 'Anzeigen', name: 'show', widget: 'boolean', default: false }
              - { label: 'Datum', name: 'date', widget: 'datetime', date_format: true, time_format: true }
  - label: 'Blog'
    name: 'blog'
    label_singular: 'Beitrag'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    delete: false
    slug: '{{year}}-{{slug}}'
    preview_path: 'blog/{{slug}}'
    media_folder: '/static/blog'
    public_folder: 'blog'
    extension: md
    editor:
      preview: false
    sortable_fields: ['published', 'title']
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - {
          label: 'Veröffenlicht am',
          name: 'published',
          widget: 'datetime',
          format: 'YYYY-MM-DDTHH:mm:SS',
          date_format: 'DD.MM.YYYY',
          time_format: 'HH:mm',
        }
      - { label: 'Zusammenfassung', name: 'description', widget: 'text' }
      - {
          label: 'Titelbild',
          name: 'featuredImage',
          widget: 'image',
          media_folder: '/static/blog',
          public_folder: 'blog',
          choose_url: false,
          allow_multiple: false,
        }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown' }
  - label: 'Veranstaltungen'
    name: 'veranstaltungen'
    label_singular: 'Veranstaltung'
    folder: 'content/veranstaltung'
    format: 'frontmatter'
    create: true
    delete: false
    slug: '{{year}}{{slug}}'
    preview_path: 'veranstaltungen/{{slug}}'
    media_folder: '/static/veranstaltungen'
    public_folder: 'veranstaltungen'
    extension: md
    editor:
      preview: false
    fields:
      - {
          label: 'ID der Veranstaltung in der Verwaltung',
          name: 'veranstaltungsID',
          widget: 'readonly',
          default: '',
          required: false,
          placeholder: 'keine',
          hint: 'Nicht veränderbar über das CMS. Kann nur von *Sebastian* oder *Tobias* angepasst werden.'
        }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - {
          label: 'Beginn',
          name: 'begin',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'DD.MM.YYYY',
          time_format: false,
          default: ""
        }
      - {
          label: 'Ende',
          name: 'ende',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'DD.MM.YYYY',
          time_format: false,
          default: ""
        }
      - { label: 'Zusammenfassung', name: 'description', widget: 'text', pattern: ['^.{0,512}$', 'max. 512 Zeichen'], hint: 'Kurze und beschreibende Zusammenfassung der Veranstaltung'}
      - {
          label: 'Titelbild',
          name: 'featuredImage',
          widget: 'image',
          media_folder: '/static/veranstaltungen',
          public_folder: 'veranstaltungen',
          choose_url: false,
          allow_multiple: false,
        }
      - label: 'Gallerie'
        label_singular: Bild
        name: 'images'
        summary: '{{fields.i}}'
        widget: 'list'
        field:
          {
            label: 'Bild',
            name: 'i',
            widget: 'image',
            media_folder: '/static/veranstaltungen',
            public_folder: 'veranstaltungen',
            choose_url: false,
            allow_multiple: true,
          }
      - {
          label: 'Ist Juleica Fortblidung',
          name: 'juleica',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Veranstaltungsort',
          name: 'veranstaltungsort',
          widget: 'string',
          hint: 'Name des Veranstaltungsortes'
        }
      - {
          label: 'Breitengrad',
          name: 'lat',
          widget: 'string',
          default: 0,
          hint: 'Verwende z.B. [latlong.net](https://www.latlong.net/) um den Breitengrad des Ortes nachzuschlagen.',
        }
      - {
          label: 'Längengrad',
          name: 'long',
          widget: 'string',
          default: 0,
          hint: 'Verwende z.B. [latlong.net](https://www.latlong.net/) um den Längengrad des Ortes nachzuschlagen.',
        }
      - { label: 'Strasse + Hausnummer', name: 'strasse', widget: 'string', required: false }
      - { label: 'PLZ', name: 'plz', widget: 'string', required: false }
      - { label: 'Ort', name: 'ort', widget: 'string', required: false }
      - {
          label: 'Mindestalter',
          required: false,
          name: 'minAlter',
          value_type: int,
          min: 0,
          max: 99,
          widget: 'number',
          default: false,
        }
      - {
          label: 'Höchstalter',
          required: false,
          name: 'maxAlter',
          value_type: int,
          min: 0,
          max: 99,
          widget: 'number',
          default: false,
        }
        # TODO: make Tags a relational field or a selection of pre defined tags
      - label: Tags
        label_singular: Tag
        name: tags
        widget: list
        summary: '{{fields.tag}}'
        default: []
        field: { label: 'Tag', name: 'tag', widget: 'string' }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown' }
      - label: Wartelisten-Hinweise
        name: warteliste
        collapsed: true
        widget: object
        hint: "**Achtung:** Diese Einstellungen hinterlegen jeweils nur einen Hinweis auf der Website. Die tatsächliche Wartelisten-Einstellung geschieht in der Verwaltung."
        fields:
          - {
              label: 'Allgemeinen Wartelisten-Hinweis anzeigen',
              name: 'allgemein',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Wartelisten-Hinweis nur für Anmeldungen von Männern anzeigen',
              name: 'männlich',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Wartelisten-Hinweis nur für Anmeldungen von Frauen anzeigen',
              name: 'weiblich',
              widget: 'boolean',
              default: false,
            }
      - label: Preise
        label_singular: Preis
        name: preise
        widget: list
        summary: '{{fields.label}}: {{fields.preis}} EUR'
        default: []
        hint: 'Keine Preise = Veranstaltung ist kostenlos.'
        fields:
          - {
              label: 'Titel',
              name: 'label',
              widget: 'select',
              options: ['Frühbucher', 'Normal', 'Last-Minute'],
              default: 'Normal',
            }
          - {
              label: 'Gilt ab',
              name: 'begin',
              widget: 'datetime',
              format: 'YYYY-MM-DD',
              date_format: 'DD.MM.YYYY',
              time_format: false,
              required: false,
              default: null,
            }
          - {
              label: 'Gilt bis',
              name: 'ende',
              widget: 'datetime',
              format: 'YYYY-MM-DD',
              date_format: 'DD.MM.YYYY',
              time_format: false,
              required: false,
              default: null,
            }
          - {
              label: 'Preis',
              name: 'preis',
              widget: 'number',
              value_type: int,
              min: 0,
            }
      - label: Anmelde-Formular
        name: anmeldung
        widget: object
        fields:
          - {
              label: 'Anmelde-Formular sichtbar',
              name: 'visible',
              widget: 'boolean',
              default: false,
              hint: 'Aktiviere diese Option um eine anmeldung für die Veranstaltung grundsätzlich zu ermöglichen.'
            }
          - {
              label: 'Anmeldung sperren',
              name: 'disabled',
              widget: 'boolean',
              default: false,
              hint: 'Zeigt anstelle des Anmelde-Formulars einen Hinweis an, dass die Anmeldung zur Zeit gesperrt ist.'
            }
          - {
              label: 'Countdown für die Anmeldung',
              hint: 'Zeigt anstelle des Anmelde-Formulars einen Countdown an und ermöglicht eine Anmeldung erst nach dem angegebenen Zeitpunkt. Um den Countdown zu "deaktivieren", setzte ihn auf ein Datum in der Verangenheit.',
              name: 'startAt',
              widget: 'datetime',
              date_format: 'DD.MM.YYYY',
              time_format: 'HH:mm',
              default: "",
              required: false,
              format: 'YYYY-MM-DDTHH:mm:SSZ',
              picker_utc: false
            }
          - {
              label: 'Verpflegungspräferenzen mit abfragen',
              hint: 'Grundsätzlich benötigt wenn für die Teilnehmer Essen zubereitet werden soll',
              name: 'hatEssen',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Gesundheitsinformationen mit abfragen',
              name: 'hatGesundheit',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Erlaubnis zum Boot fahren mit abfragen',
              hint: 'Ggf. relevant für Anmeldungen von Minderjährigen',
              name: 'hatErlaubnisBoot',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Erlaubnis zum Klettern mit abfragen',
              hint: 'Ggf. relevant für Anmeldungen von Minderjährigen',
              name: 'hatErlaubnisKlettern',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Erlaubnis zum Fahrradfahren mit abfragen',
              hint: 'Ggf. relevant für Anmeldungen von Minderjährigen',
              name: 'hatErlaubnisFahrrad',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Erlaubnis zum Schwimmen mit abfragen',
              hint: 'Ggf. relevant für Anmeldungen von Minderjährigen',
              name: 'hatErlaubnisSchwimmen',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Erlaubnis zum Entfernen mind. zu dritt mit abfragen',
              hint: 'Ggf. relevant für Anmeldungen von Minderjährigen',
              name: 'hatErlaubnisSichEntfernen',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Zustimmung zur Übermittlung der Kontaktdaten an andere Teilnehmer einholen',
              hint: 'z.B. zum bilden von Fahrgemeinschaften',
              name: 'hatFahrgemeinschaft',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Hinweis zum Anweisen des Kindes den Anordungen des Freizeitleiters folge zu leisten',
              hint: 'Grundsätzlich bei Freizeiten für Minderjährige benötigt',
              name: 'hatFreizeitleitung',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Ab Jahrgang',
              name: 'jahrgangMin',
              value_type: int,
              min: 1900,
              widget: 'number',
              required: false,
            }
          - {
              label: 'bis Jahrgang',
              name: 'jahrgangMax',
              value_type: int,
              min: 1900,
              widget: 'number',
              required: false,
            }
