name: ci

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: yarn generate
        env:
          CI: true

      - name: OutCheck
        run: cd dist && tree

      - name: Lighthouse Audits
        run: |
          yarn lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
          LHCI_TOKEN: ${{secrets.LHCI_TOKEN}}
          CI: true
