name: ci

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd
        with:
          version: 6.27.1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm i

      - name: Build
        run: pnpm run generate
        env:
          CI: true

      - name: OutCheck
        run: cd dist && tree
        
      - name: Install Server
        run: pnpm i -g --only=prod https-localhost

      - name: Lighthouse Audits
        run: pnpm lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
          LHCI_TOKEN: ${{secrets.LHCI_TOKEN}}
          CI: true
