name: CI

on:
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [preview-content]

concurrency: ci

env:
  EC_SET_BASE: ${{((github.event_name == 'push' && github.ref_name == 'static') && '/') || ((github.event_name == 'push' && github.ref_name != 'static') && '/${{github.ref_name}}/') || ((github.event_name != 'push') && '/${{github.event.client_payload.branch}}/')}}
  EC_TARGET_DEPLOY: ${{((github.event_name == 'push' && github.ref_name == 'static') || 'www') || ((github.event_name == 'push' && github.ref_name != 'static') || 'dev') || ((github.event_name != 'push') || 'preview')}}

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Select cms-version
        run: cd cms-content && git checkout ${{github.event.client_payload.branch}} && cd ..
        if: github.event_name != 'push'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Generate
        run: yarn generate
      - name: Symlinks
        run: |
          cp -r ./cms-content/static/blog ./_blog
          cp -r ./cms-content/static/veranstaltungen ./_veranstaltungen
          cp -r ./cms-content/static/download ./_download
          cp -r ./cms-content/static/old ./_old
          rm -r ./dist/blog
          rm -r ./dist/veranstaltungen
          rm -r ./dist/download
          cp -r ./_blog ./dist/blog
          cp -r ./_veranstaltungen ./dist/veranstaltungen
          cp -r ./_download ./dist/download
          cp -r ./_old ./dist/old
      - name: Deploy to ec-nordbund.de
        env:
          dest: 'deployer@ec-nordbund.de:/samba_share/preview.ec-nordbund.de/${{ github.event.client_payload.branch }}'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          ssh -i ./deploy_key -o StrictHostKeyChecking=no deployer@ec-nordbund.de "/bin/mkdir -p /samba_share/${{env.EC_TARGET_DEPLOY}}.ec-nordbund.de${{env.EC_SET_BASE}}"
          rsync -chrvz --stats --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            ./dist/ /samba_share/${{env.EC_TARGET_DEPLOY}}.ec-nordbund.de${{env.EC_SET_BASE}}
      - name: Deploy to ec-nordbund.de
        if: github.event_name == 'push'
        env:
          dest: 'deployer@ec-nordbund.de:/samba_share/preview.ec-nordbund.de/${{ github.event.client_payload.branch }}'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          ssh -i ./deploy_key -o StrictHostKeyChecking=no deployer@ec-nordbund.de "/bin/mkdir -p /samba_share/lighthouse.ec-nordbund.de"
          rsync -chrvz --stats --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            ./dist/ /samba_share/lighthouse.ec-nordbund.de
      - name: Lighthouse Audits
        if: github.event_name == 'push'
        run: yarn lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
          LHCI_TOKEN: ${{secrets.LHCI_TOKEN}}
          CI: true
