name: Deploy Website

on:
  push:
    branches: [ static ]

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn generate
        env:
          CI: true
          
      - name: debug
        run: ls -l
      - name: Remove Symlinks
        run: unlink ./dist/blog && unlink ./dist/veranstaltungen && unlink ./dist/downloads
      - name: Copy symlink content
        run: cp -r ./content-cms/static/blog ./dist/blog && cp -r ./content-cms/static/veranstaltungen ./dist/veranstaltungen && cp -r ./content-cms/static/downloads ./dist/downloads

      - name: Deploy to ec-nordbund.de
        env:
          dest: 'deployer@ec-nordbund.de:/samba_share/www.ec-nordbund.de'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chrvz --stats --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            ./dist/ ${{ env.dest }}
