name: Deploy Preview

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn generate
        env:
          CI: true
          EC_SET_BASE: /${{ github.ref_name }}/
      - name: smylinks
        run: |
          cp -r ./cms-content/static/blog ./_blog
          cp -r ./cms-content/static/veranstaltungen ./_veranstaltungen
          cp -r ./cms-content/static/download ./_download
          cp -r ./cms-content/static/old ./_old
          rm -r ./dist/blog
          rm -r ./dist/veranstaltungen
          rm -r ./dist/download
          cp -r ./_blog ./dist/blog
          cp -r ./_veranstaltungen ./dist/veranstaltungen
          cp -r ./_download ./dist/download
          cp -r ./_old ./dist/old
      - name: Deploy to ec-nordbund.de
        env:
          dest: 'deployer@ec-nordbund.de:/samba_share/preview.ec-nordbund.de/${{ github.ref_name }}'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          ssh -i ./deploy_key -o StrictHostKeyChecking=no deployer@ec-nordbund.de "/bin/mkdir -p /samba_share/preview.ec-nordbund.de/${{ github.ref_name }}"
          rsync -chrvz --stats --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            ./dist/ ${{ env.dest }}
