name: Update on new content dispatch

on:
  repository_dispatch:
    types: [merge-content]

jobs:
  mergeContent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule
        uses: actions/checkout@v3
      
      - run: echo "Content updated"
          
