name: Update on new content dispatch

on:
  repository_dispatch:
    types: [merge-content]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
          submodules: true

      - name: Update submodules content
        run: git submodule update --remote --recursive


      - name: Pull the content
        run: git pull
        
      - name: Update submodules index
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: apply automatic changed content
          # branch: static
          

