name: Update on new content dispatch

on:
  repository_dispatch:
    types: [merge-content]

jobs:
  mergeContent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
          submodules: true

      - name: Update submodules content
        run: git submodule update --remote --recursive

      - name: Pull the content
        run: git pull
        
      - name: Update submodules index
        uses: stefanzweifel/git-auto-commit-action@v4.14.0
        with:
          commit_message: apply automatic changed content
          # branch: static
          
